[package]
name = "frost_playground"
version = "0.1.0"
edition = "2021"

[dependencies]
bs58 = "0.5.1"
eyre = "0.6.12"
frost-ristretto255 = { version = "2.1.0", features = ["cheater-detection"] }
rand = "^0.8.0"
sha2 = "0.10.8"
tokio = { version = "1.43.0", features = ["full"] }
